// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1yXiJt98tjzYedHfbOp9tlzb5-j8flI',
    appId: '1:954547536575:web:c20285a9b83ee5142cbc0a',
    messagingSenderId: '954547536575',
    projectId: 'jct-flutter',
    authDomain: 'jct-flutter.firebaseapp.com',
    databaseURL: 'https://jct-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'jct-flutter.appspot.com',
    measurementId: 'G-TN9MQ92HHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF10-kdWWUkaDKDxFzJkvJIyHrBc3Z3SY',
    appId: '1:954547536575:android:f70f618372d6f7bc2cbc0a',
    messagingSenderId: '954547536575',
    projectId: 'jct-flutter',
    databaseURL: 'https://jct-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'jct-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxTmBUJN8_e3nBAQlQ5SkHcuiEEUQmvM',
    appId: '1:954547536575:ios:422b9b6324518b542cbc0a',
    messagingSenderId: '954547536575',
    projectId: 'jct-flutter',
    databaseURL: 'https://jct-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'jct-flutter.appspot.com',
    iosBundleId: 'com.example.jct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXxTmBUJN8_e3nBAQlQ5SkHcuiEEUQmvM',
    appId: '1:954547536575:ios:422b9b6324518b542cbc0a',
    messagingSenderId: '954547536575',
    projectId: 'jct-flutter',
    databaseURL: 'https://jct-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'jct-flutter.appspot.com',
    iosBundleId: 'com.example.jct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1yXiJt98tjzYedHfbOp9tlzb5-j8flI',
    appId: '1:954547536575:web:e59deb54878fc18f2cbc0a',
    messagingSenderId: '954547536575',
    projectId: 'jct-flutter',
    authDomain: 'jct-flutter.firebaseapp.com',
    databaseURL: 'https://jct-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'jct-flutter.appspot.com',
    measurementId: 'G-DJ7LLY8PKR',
  );
}
