// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyh6QwHlccQ2Q4jyHNQlFEyu7h-lu3Clk',
    appId: '1:597306534586:android:3f729788b71c256eaff083',
    messagingSenderId: '597306534586',
    projectId: 'jct-forked',
    storageBucket: 'jct-forked.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc7tcdUAYEEQxgCbjA1GeVXJxHyWwqnwo',
    appId: '1:597306534586:web:536ea0d7d661d9f9aff083',
    messagingSenderId: '597306534586',
    projectId: 'jct-forked',
    authDomain: 'jct-forked.firebaseapp.com',
    storageBucket: 'jct-forked.appspot.com',
    measurementId: 'G-ZWGJWR5XZR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr-ERCI7DNlLy4E3xf-gM98R1g-LclXRU',
    appId: '1:597306534586:ios:059a68450bed160caff083',
    messagingSenderId: '597306534586',
    projectId: 'jct-forked',
    storageBucket: 'jct-forked.appspot.com',
    iosBundleId: 'com.example.jct',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr-ERCI7DNlLy4E3xf-gM98R1g-LclXRU',
    appId: '1:597306534586:ios:059a68450bed160caff083',
    messagingSenderId: '597306534586',
    projectId: 'jct-forked',
    storageBucket: 'jct-forked.appspot.com',
    iosBundleId: 'com.example.jct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc7tcdUAYEEQxgCbjA1GeVXJxHyWwqnwo',
    appId: '1:597306534586:web:3b15b8407231df65aff083',
    messagingSenderId: '597306534586',
    projectId: 'jct-forked',
    authDomain: 'jct-forked.firebaseapp.com',
    storageBucket: 'jct-forked.appspot.com',
    measurementId: 'G-2EP0JH89H3',
  );

}